// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PackageData struct {
	Records              []*EncodedRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	AgentId              string           `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	IntranetIpv4         []string         `protobuf:"bytes,3,rep,name=intranet_ipv4,json=intranetIpv4,proto3" json:"intranet_ipv4,omitempty"`
	ExtranetIpv4         []string         `protobuf:"bytes,4,rep,name=extranet_ipv4,json=extranetIpv4,proto3" json:"extranet_ipv4,omitempty"`
	IntranetIpv6         []string         `protobuf:"bytes,5,rep,name=intranet_ipv6,json=intranetIpv6,proto3" json:"intranet_ipv6,omitempty"`
	ExtranetIpv7         []string         `protobuf:"bytes,6,rep,name=extranet_ipv7,json=extranetIpv7,proto3" json:"extranet_ipv7,omitempty"`
	Hostname             string           `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version              string           `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	Product              string           `protobuf:"bytes,9,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PackageData) Reset()         { *m = PackageData{} }
func (m *PackageData) String() string { return proto.CompactTextString(m) }
func (*PackageData) ProtoMessage()    {}
func (*PackageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *PackageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageData.Unmarshal(m, b)
}
func (m *PackageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageData.Marshal(b, m, deterministic)
}
func (m *PackageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageData.Merge(m, src)
}
func (m *PackageData) XXX_Size() int {
	return xxx_messageInfo_PackageData.Size(m)
}
func (m *PackageData) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageData.DiscardUnknown(m)
}

var xxx_messageInfo_PackageData proto.InternalMessageInfo

func (m *PackageData) GetRecords() []*EncodedRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *PackageData) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *PackageData) GetIntranetIpv4() []string {
	if m != nil {
		return m.IntranetIpv4
	}
	return nil
}

func (m *PackageData) GetExtranetIpv4() []string {
	if m != nil {
		return m.ExtranetIpv4
	}
	return nil
}

func (m *PackageData) GetIntranetIpv6() []string {
	if m != nil {
		return m.IntranetIpv6
	}
	return nil
}

func (m *PackageData) GetExtranetIpv7() []string {
	if m != nil {
		return m.ExtranetIpv7
	}
	return nil
}

func (m *PackageData) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *PackageData) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PackageData) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

type EncodedRecord struct {
	DataType             int32    `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 *Payload `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncodedRecord) Reset()         { *m = EncodedRecord{} }
func (m *EncodedRecord) String() string { return proto.CompactTextString(m) }
func (*EncodedRecord) ProtoMessage()    {}
func (*EncodedRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *EncodedRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncodedRecord.Unmarshal(m, b)
}
func (m *EncodedRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncodedRecord.Marshal(b, m, deterministic)
}
func (m *EncodedRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodedRecord.Merge(m, src)
}
func (m *EncodedRecord) XXX_Size() int {
	return xxx_messageInfo_EncodedRecord.Size(m)
}
func (m *EncodedRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodedRecord.DiscardUnknown(m)
}

var xxx_messageInfo_EncodedRecord proto.InternalMessageInfo

func (m *EncodedRecord) GetDataType() int32 {
	if m != nil {
		return m.DataType
	}
	return 0
}

func (m *EncodedRecord) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *EncodedRecord) GetData() *Payload {
	if m != nil {
		return m.Data
	}
	return nil
}

type Record struct {
	DataType             int32    `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 *Payload `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{2}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetDataType() int32 {
	if m != nil {
		return m.DataType
	}
	return 0
}

func (m *Record) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Record) GetData() *Payload {
	if m != nil {
		return m.Data
	}
	return nil
}

type Payload struct {
	Fields               map[string]string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{3}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetFields() map[string]string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Command struct {
	Task                 *Task     `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Configs              []*Config `protobuf:"bytes,3,rep,name=configs,proto3" json:"configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{4}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *Command) GetConfigs() []*Config {
	if m != nil {
		return m.Configs
	}
	return nil
}

type Task struct {
	DataType             int32    `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	ObjectName           string   `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{5}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetDataType() int32 {
	if m != nil {
		return m.DataType
	}
	return 0
}

func (m *Task) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func (m *Task) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Task) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Config struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Sha256               string   `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	DownloadUrls         []string `protobuf:"bytes,6,rep,name=download_urls,json=downloadUrls,proto3" json:"download_urls,omitempty"`
	Detail               string   `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{6}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Config) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Config) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Config) GetSha256() string {
	if m != nil {
		return m.Sha256
	}
	return ""
}

func (m *Config) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Config) GetDownloadUrls() []string {
	if m != nil {
		return m.DownloadUrls
	}
	return nil
}

func (m *Config) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*PackageData)(nil), "grpc.PackageData")
	proto.RegisterType((*EncodedRecord)(nil), "grpc.EncodedRecord")
	proto.RegisterType((*Record)(nil), "grpc.Record")
	proto.RegisterType((*Payload)(nil), "grpc.Payload")
	proto.RegisterMapType((map[string]string)(nil), "grpc.Payload.FieldsEntry")
	proto.RegisterType((*Command)(nil), "grpc.Command")
	proto.RegisterType((*Task)(nil), "grpc.Task")
	proto.RegisterType((*Config)(nil), "grpc.Config")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcf, 0x6f, 0xd3, 0x3e,
	0x14, 0xff, 0x66, 0x49, 0x93, 0xe6, 0x65, 0x95, 0xbe, 0x18, 0x84, 0xbc, 0x81, 0xa0, 0x04, 0x09,
	0xe5, 0xc2, 0x04, 0x61, 0x74, 0xc0, 0x81, 0x03, 0x63, 0x48, 0xbb, 0xa0, 0x11, 0x95, 0x0b, 0x97,
	0xca, 0x4b, 0xdc, 0x2e, 0x34, 0xb1, 0x23, 0xdb, 0xed, 0xe8, 0xdf, 0x86, 0xf8, 0xdf, 0x90, 0xed,
	0xa4, 0x4b, 0x99, 0xc4, 0x91, 0x53, 0xde, 0xe7, 0xf3, 0x3e, 0x7e, 0x7e, 0xbf, 0x1c, 0x80, 0x85,
	0x68, 0xf2, 0xa3, 0x46, 0x70, 0xc5, 0x91, 0xa7, 0xed, 0xf8, 0xe7, 0x1e, 0x44, 0x17, 0x24, 0x5f,
	0x92, 0x05, 0xfd, 0x48, 0x14, 0x41, 0xcf, 0x21, 0x10, 0x34, 0xe7, 0xa2, 0x90, 0xd8, 0x19, 0xbb,
	0x49, 0x94, 0xde, 0x3d, 0x32, 0x67, 0xce, 0x58, 0xce, 0x0b, 0x5a, 0x64, 0xc6, 0x97, 0x75, 0x1a,
	0x74, 0x00, 0x43, 0xb2, 0xa0, 0x4c, 0xcd, 0xca, 0x02, 0xef, 0x8d, 0x9d, 0x24, 0xcc, 0x02, 0x83,
	0xcf, 0x0b, 0xf4, 0x14, 0x46, 0x25, 0x53, 0x82, 0x30, 0xaa, 0x66, 0x65, 0xb3, 0x3e, 0xc6, 0xee,
	0xd8, 0x4d, 0xc2, 0x6c, 0xbf, 0x23, 0xcf, 0x9b, 0xf5, 0xb1, 0x16, 0xd1, 0x1f, 0x7d, 0x91, 0x67,
	0x45, 0x1d, 0xd9, 0x89, 0xfa, 0x91, 0x26, 0x78, 0x70, 0x2b, 0xd2, 0xe4, 0xcf, 0x48, 0x27, 0xd8,
	0xbf, 0x15, 0xe9, 0x04, 0x1d, 0xc2, 0xf0, 0x8a, 0x4b, 0xc5, 0x48, 0x4d, 0x71, 0x60, 0xd2, 0xdd,
	0x62, 0x84, 0x21, 0x58, 0x53, 0x21, 0x4b, 0xce, 0xf0, 0xd0, 0x56, 0xd2, 0x42, 0xed, 0x69, 0x04,
	0x2f, 0x56, 0xb9, 0xc2, 0xa1, 0xf5, 0xb4, 0x30, 0xae, 0x61, 0xb4, 0xd3, 0x18, 0xf4, 0x00, 0xc2,
	0x82, 0x28, 0x32, 0x53, 0x9b, 0x86, 0x62, 0x67, 0xec, 0x24, 0x83, 0x6c, 0xa8, 0x89, 0xe9, 0xa6,
	0xa1, 0xe8, 0x21, 0x84, 0xaa, 0xac, 0xa9, 0x54, 0xa4, 0x6e, 0x4c, 0xb7, 0xdc, 0xec, 0x86, 0x40,
	0x4f, 0xc0, 0xd3, 0x4a, 0xec, 0x8e, 0x9d, 0x24, 0x4a, 0x47, 0xb6, 0xed, 0x17, 0x64, 0x53, 0x71,
	0x52, 0x64, 0xc6, 0x15, 0xcf, 0xc1, 0xff, 0x27, 0xf7, 0x5c, 0x43, 0xd0, 0x12, 0xe8, 0x25, 0xf8,
	0xf3, 0x92, 0x56, 0xdb, 0x75, 0x38, 0xd8, 0xd1, 0x1f, 0x7d, 0x32, 0xbe, 0x33, 0xa6, 0xc4, 0x26,
	0x6b, 0x85, 0x87, 0x6f, 0x21, 0xea, 0xd1, 0xe8, 0x7f, 0x70, 0x97, 0x74, 0x63, 0x92, 0x0c, 0x33,
	0x6d, 0xa2, 0x7b, 0x30, 0x58, 0x93, 0x6a, 0x45, 0xdb, 0x8d, 0xb1, 0xe0, 0xdd, 0xde, 0x1b, 0x27,
	0xfe, 0x02, 0xc1, 0x29, 0xaf, 0x6b, 0xc2, 0x0a, 0xf4, 0x08, 0x3c, 0x45, 0xe4, 0xd2, 0x68, 0xa2,
	0x14, 0xec, 0xb5, 0x53, 0x22, 0x97, 0x99, 0xe1, 0xd1, 0x33, 0x08, 0x72, 0xce, 0xe6, 0xe5, 0x42,
	0x9a, 0xc5, 0x8a, 0xd2, 0x7d, 0x2b, 0x39, 0x35, 0x64, 0xd6, 0x39, 0x63, 0x06, 0x9e, 0x3e, 0xf5,
	0xf7, 0x8e, 0x3d, 0x86, 0x88, 0x5f, 0x7e, 0xa7, 0xb9, 0x9a, 0x99, 0xd5, 0xb0, 0x79, 0x81, 0xa5,
	0x3e, 0xeb, 0xe5, 0x40, 0xbd, 0xa6, 0x85, 0xb6, 0x4b, 0xba, 0x0c, 0xc5, 0x97, 0x94, 0x61, 0xcf,
	0x96, 0x61, 0x40, 0xfc, 0xcb, 0x01, 0xdf, 0xe6, 0xa0, 0x0f, 0x99, 0x70, 0xb6, 0x74, 0x63, 0x6b,
	0xce, 0x64, 0x60, 0xaf, 0x30, 0x76, 0x7f, 0xf3, 0xdc, 0xdd, 0xcd, 0xbb, 0x0f, 0xbe, 0xbc, 0x22,
	0xe9, 0xeb, 0x49, 0x7b, 0x47, 0x8b, 0xf4, 0x84, 0x65, 0xb9, 0x60, 0x44, 0xad, 0x04, 0xc5, 0x03,
	0xe3, 0xba, 0x21, 0xf4, 0x53, 0x28, 0xf8, 0x35, 0xd3, 0x03, 0x9a, 0xad, 0x44, 0x25, 0xbb, 0xa7,
	0xd0, 0x91, 0x5f, 0x45, 0x25, 0x75, 0xe8, 0x82, 0x2a, 0x52, 0x56, 0xed, 0x43, 0x68, 0x51, 0xfa,
	0x1e, 0x86, 0x53, 0x41, 0x98, 0x9c, 0x53, 0x81, 0xd2, 0x9e, 0x7d, 0xa7, 0x1b, 0xfc, 0xf6, 0x5f,
	0x71, 0x38, 0xea, 0x3a, 0x6e, 0x26, 0x16, 0xff, 0x97, 0x38, 0x2f, 0x9c, 0x0f, 0xc1, 0xb7, 0x81,
	0xf9, 0xbf, 0x5c, 0xfa, 0xe6, 0xf3, 0xea, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xfb, 0xab,
	0xca, 0x74, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransferClient is the client API for Transfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransferClient interface {
	Transfer(ctx context.Context, opts ...grpc.CallOption) (Transfer_TransferClient, error)
}

type transferClient struct {
	cc *grpc.ClientConn
}

func NewTransferClient(cc *grpc.ClientConn) TransferClient {
	return &transferClient{cc}
}

func (c *transferClient) Transfer(ctx context.Context, opts ...grpc.CallOption) (Transfer_TransferClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Transfer_serviceDesc.Streams[0], "/grpc.Transfer/Transfer", opts...)
	if err != nil {
		return nil, err
	}
	x := &transferTransferClient{stream}
	return x, nil
}

type Transfer_TransferClient interface {
	Send(*PackageData) error
	Recv() (*Command, error)
	grpc.ClientStream
}

type transferTransferClient struct {
	grpc.ClientStream
}

func (x *transferTransferClient) Send(m *PackageData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transferTransferClient) Recv() (*Command, error) {
	m := new(Command)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransferServer is the server API for Transfer service.
type TransferServer interface {
	Transfer(Transfer_TransferServer) error
}

// UnimplementedTransferServer can be embedded to have forward compatible implementations.
type UnimplementedTransferServer struct {
}

func (*UnimplementedTransferServer) Transfer(srv Transfer_TransferServer) error {
	return status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}

func RegisterTransferServer(s *grpc.Server, srv TransferServer) {
	s.RegisterService(&_Transfer_serviceDesc, srv)
}

func _Transfer_Transfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransferServer).Transfer(&transferTransferServer{stream})
}

type Transfer_TransferServer interface {
	Send(*Command) error
	Recv() (*PackageData, error)
	grpc.ServerStream
}

type transferTransferServer struct {
	grpc.ServerStream
}

func (x *transferTransferServer) Send(m *Command) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transferTransferServer) Recv() (*PackageData, error) {
	m := new(PackageData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Transfer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Transfer",
	HandlerType: (*TransferServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transfer",
			Handler:       _Transfer_Transfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
